name: movitty
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  
  #Core
  equatable: ^2.0.5
  get_it: ^7.6.4

  #Network Dependencies
  vexana: ^3.5.4

  #State
  flutter_bloc: ^8.1.3

  # Config
  easy_localization: ^3.0.3

  #Utility
  easy_logger: ^0.0.2
  logger: ^2.0.2+1
  kartal: ^3.5.0
  google_fonts: ^6.1.0

  #Navigation
  auto_route: ^7.8.4

  widgets:
    path: module/widgets

  # Modules
  gen:
    path: module/gen
  common:
    path: module/common
  core:
    path: module/core

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  device_preview: ^1.1.0
  mockito: ^5.4.2
  bloc_test: ^9.1.4
  patrol: ^2.3.1



flutter:

  uses-material-design: true
